sudo: required
env:
  - REPO_NAME=${TRAVIS_REPO_SLUG#*/}

git:
  depth: false
  quiet: true

services:
  - docker

before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull opensciencegrid/osg-build

script:
  - mkdir /tmp/python-deps
  - wget https://vdt.cs.wisc.edu/upstream/xcache/1.3.0/python-deps/numpy-1.16.6-cp27-cp27mu-manylinux1_x86_64.whl -O /tmp/python-deps/numpy-1.16.6-cp27-cp27mu-manylinux1_x86_64.whl
  - docker run -v $(pwd):/$REPO_NAME -e REPO_NAME=$REPO_NAME --cap-add=SYS_ADMIN --volume /tmp/python-deps:/u/rpmbuild/SOURCES opensciencegrid/osg-build build-from-github

